# 工作流名称
name: sync docker images
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

#     - name: Login to Docker Hub
#       uses: docker/login-action@v2.2.0
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         logout: false
        
    - name: Save Image
      run: |
        #!/usr/bin/env bash
        # skopeo copy docker://gcr.io/kaniko-project/executor:v1.13.0 docker://weiyigeek/kaniko-executor:v1.13.0
        docker pull ubuntu:24.04
        docker save ubuntu:24.04 -o ubuntu-24.04.tar
    - name: List
      run: ls -la

#      with:
#        name: my-artifact
#        path: ubuntu-24.04.tar

    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: ubuntu-24.04.tar
        path: |  
          ubuntu-24.04.tar  
        retention-days: 7  # 设置保留周期（默认 90 天）  
